# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-08-27 12:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paypalentrytransaction',
            name='payment_type',
            field=models.CharField(choices=[('video', 'video'), ('selected', 'selected'), ('withdrawal', 'withdrawal')], max_length=255),
        ),
    ]
