# Generated by Django 2.0.3 on 2018-04-23 16:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_auto_20160827_1333'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paypalentrytransaction',
            name='entry',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='entries.Entry'),
        ),
    ]
