---
- name: Setup Virtualenv
  pip: executable=pip3 virtualenv={{ virtualenv_path }} requirements={{ project_root_path }}/requirements.txt

- name: Install some dev tools
  become: true
  become_user: root
  pip: name={{ item }} executable=pip3 virtualenv={{ virtualenv_path }}
  with_items:
    - ipdb
    - ipython
    - django-extensions

- name: Django db
  django_manage: command={{ item }} app_path={{ project_root_path }} virtualenv={{ virtualenv_path }}
  with_items:
    - migrate

- name: Populate database
  django_manage: command={{ item }} app_path={{ project_root_path }} virtualenv={{ virtualenv_path }}
  with_items:
    - setup_fb


