# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-08-15 21:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20160829_2009'),
    ]

    operations = [
        migrations.AlterField(
            model_name='onlinedisclaimer',
            name='waiver_terms',
            field=models.CharField(default='\nI hereby declare that I have read and understood all the rules of the Pole Performance categories and agree to represent the competition in a professional manner during and prior to the event.\n\nI agree that I am available all day on March 11th 2018.\n\nI understand that my entry will not be accepted until I have paid the appropriate entry fee and that all judges’ decisions are final.\n\nI am taking part in Pole Performance entirely at my own risk. Pole Performance is not responsible for any injury/death caused by my participation in this event.\n\nI assume full responsibility for my participation, knowing the risks involved, and I hold Pole Performance and Carnegie Hall staff/volunteers free from any liability.\n\nI am not pregnant and have not been pregnant in the past three months.\n\nI am deemed physically fit to participate in exercise and have no health or heart conditions that may affect my ability to participate safely in a pole competition.\n\nI give permission for my photo to be taken and used for advertisement and promotional purposes for Pole Performance.\n\nI agree to the above T & C’s and release of liability. I have fully read and understood all information given to me by Pole Performance and free and  voluntarily sign without any inducement.\n', max_length=2048),
        ),
    ]
