# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-08-25 21:01
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0003_onlinedisclaimer_gender'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pole_school', models.CharField(blank=True, max_length=255, null=True)),
                ('dob', models.DateField(verbose_name='date of birth')),
                ('address', models.CharField(max_length=512)),
                ('postcode', models.CharField(max_length=10)),
                ('phone', models.CharField(max_length=255)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
