# Generated by Django 2.2.5 on 2019-10-19 08:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0005_auto_20191017_1619'),
    ]

    operations = [
        migrations.AddField(
            model_name='onlinedisclaimer',
            name='entry_year',
            field=models.CharField(default='2020', max_length=4),
        ),
        migrations.AlterField(
            model_name='onlinedisclaimer',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='online_disclaimer', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='onlinedisclaimer',
            unique_together={('user', 'entry_year')},
        ),
    ]
