# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-08-28 21:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_auto_20160826_2204'),
    ]

    operations = [
        migrations.RenameField(
            model_name='onlinedisclaimer',
            old_name='emergency_contact1_name',
            new_name='emergency_contact_name',
        ),
        migrations.RenameField(
            model_name='onlinedisclaimer',
            old_name='emergency_contact1_phone',
            new_name='emergency_contact_phone',
        ),
        migrations.RenameField(
            model_name='onlinedisclaimer',
            old_name='emergency_contact1_relationship',
            new_name='emergency_contact_relationship',
        ),
        migrations.RemoveField(
            model_name='onlinedisclaimer',
            name='address',
        ),
        migrations.RemoveField(
            model_name='onlinedisclaimer',
            name='age_over_18_confirmed',
        ),
        migrations.RemoveField(
            model_name='onlinedisclaimer',
            name='allergies',
        ),
        migrations.RemoveField(
            model_name='onlinedisclaimer',
            name='allergies_details',
        ),
        migrations.RemoveField(
            model_name='onlinedisclaimer',
            name='disclaimer_terms',
        ),
        migrations.RemoveField(
            model_name='onlinedisclaimer',
            name='dob',
        ),
        migrations.RemoveField(
            model_name='onlinedisclaimer',
            name='emergency_contact2_name',
        ),
        migrations.RemoveField(
            model_name='onlinedisclaimer',
            name='emergency_contact2_phone',
        ),
        migrations.RemoveField(
            model_name='onlinedisclaimer',
            name='emergency_contact2_relationship',
        ),
        migrations.RemoveField(
            model_name='onlinedisclaimer',
            name='gender',
        ),
        migrations.RemoveField(
            model_name='onlinedisclaimer',
            name='home_phone',
        ),
        migrations.RemoveField(
            model_name='onlinedisclaimer',
            name='joint_problems',
        ),
        migrations.RemoveField(
            model_name='onlinedisclaimer',
            name='joint_problems_details',
        ),
        migrations.RemoveField(
            model_name='onlinedisclaimer',
            name='medical_conditions',
        ),
        migrations.RemoveField(
            model_name='onlinedisclaimer',
            name='medical_conditions_details',
        ),
        migrations.RemoveField(
            model_name='onlinedisclaimer',
            name='medical_treatment_permission',
        ),
        migrations.RemoveField(
            model_name='onlinedisclaimer',
            name='medical_treatment_terms',
        ),
        migrations.RemoveField(
            model_name='onlinedisclaimer',
            name='mobile_phone',
        ),
        migrations.RemoveField(
            model_name='onlinedisclaimer',
            name='name',
        ),
        migrations.RemoveField(
            model_name='onlinedisclaimer',
            name='over_18_statement',
        ),
        migrations.RemoveField(
            model_name='onlinedisclaimer',
            name='postcode',
        ),
        migrations.AddField(
            model_name='onlinedisclaimer',
            name='waiver_terms',
            field=models.CharField(default='\nI hereby declare that I have read and understood all the rules of the Pole\nPerformance categories and agree to represent the competition in a\nprofessional manner during and prior to the event.\n\nI agree that I am available all day on March 12th 2017.\n\nI understand that my entry will not be accepted until I have paid the\nappropriate entry fee and that all judges’ decisions are final.\n\nI am taking part in Pole Performance entirely at my own risk. Pole Performance\nis not responsible for any injury/death caused by my participation in this\nevent.\n\nI assume full responsibility for my participation, knowing the risks involved,\nand I hold Pole Performance and Carnegie Hall staff/volunteers free from any\nliability.\n\nI am not pregnant and have not been pregnant in the past three months.\n\nI am deemed physically fit to participate in exercise and have no health or\nheart conditions that may affect my ability to participate safely in a pole\ncompetition.\n\nI give permission for my photo to be taken and used for advertisement and\npromotional purposes for Pole Performance.\n\nI agree to the above T&amp;C’s and release of liability. I have fully read\nand understood all information given to me by Pole Performance and free and\nvoluntarily sign without any inducement.\n\n', max_length=2048),
        ),
    ]
