# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-08-16 19:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20160801_1541'),
    ]

    operations = [
        migrations.AddField(
            model_name='onlinedisclaimer',
            name='gender',
            field=models.CharField(choices=[('female', 'Female'), ('male', 'Male')], default='female', max_length=20),
        ),
    ]
