# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-08-29 19:11
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('entries', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='entry',
            options={'verbose_name_plural': 'entries'},
        ),
        migrations.AddField(
            model_name='entry',
            name='notified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='entry',
            name='notified_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='entry',
            name='reminder_sent',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='entry',
            name='withdrawal_fee_paid',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='entry',
            name='withdrawn',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='entry',
            name='biography',
            field=models.TextField(blank=True, help_text='How long have you been poling? Previous titles? Why you have entered? Any relevant information about yourself? How would you describe your style?', null=True, verbose_name='Short bio'),
        ),
        migrations.AlterField(
            model_name='entry',
            name='category',
            field=models.CharField(choices=[('BEG', 'Beginner'), ('INT', 'Intermediate'), ('ADV', 'Advanced'), ('PRO', 'Professional'), ('DOU', 'Doubles'), ('MEN', 'Mens')], default='BEG', max_length=3),
        ),
        migrations.AlterField(
            model_name='entry',
            name='entry_year',
            field=models.CharField(choices=[('2017', '2017'), ('2018', '2018'), ('2019', '2019'), ('2020', '2020'), ('2021', '2021')], default='2017', max_length=4),
        ),
        migrations.AlterField(
            model_name='entry',
            name='partner_email',
            field=models.EmailField(blank=True, help_text='Ensure this is the email your doubles partner has used for their account. We will use it to ensure registration and waiver information has been received for your partner also.', max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='entry',
            name='partner_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='entry',
            name='song',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='entry',
            name='status',
            field=models.CharField(choices=[('in_progress', 'In Progress'), ('submitted', 'Submitted'), ('selected', 'Selected'), ('selected_confirmed', 'Selected - confirmed'), ('rejected', 'Rejected')], default='in_progress', max_length=20),
        ),
        migrations.AlterField(
            model_name='entry',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entries', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='entry',
            name='video_url',
            field=models.URLField(blank=True, default='', null=True),
        ),
    ]
