# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-08-19 23:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entries', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='entry',
            options={'verbose_name_plural': 'entries'},
        ),
        migrations.AlterField(
            model_name='entry',
            name='biography',
            field=models.TextField(blank=True, help_text='How long have you been poling? Previous titles? Why you have entered? Any relevant information about yourself? How would you describe your style?', null=True, verbose_name='Short bio'),
        ),
        migrations.AlterField(
            model_name='entry',
            name='entry_year',
            field=models.CharField(choices=[(2017, '2017'), (2018, '2018'), (2019, '2019'), (2020, '2020'), (2021, '2021')], default=2017, max_length=4),
        ),
        migrations.AlterField(
            model_name='entry',
            name='video_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
