# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-08-20 09:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entries', '0002_auto_20160820_0049'),
    ]

    operations = [
        migrations.AddField(
            model_name='entry',
            name='withdrawn',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='entry',
            name='entry_year',
            field=models.CharField(choices=[('2017', '2017'), ('2018', '2018'), ('2019', '2019'), ('2020', '2020'), ('2021', '2021')], default='2017', max_length=4),
        ),
        migrations.AlterField(
            model_name='entry',
            name='status',
            field=models.CharField(choices=[('in_progress', 'In Progress'), ('submitted', 'Submitted'), ('selected', 'Selected'), ('rejected', 'Unsuccessful')], default='in_progress', max_length=20),
        ),
    ]
