# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-08-15 21:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entries', '0002_auto_20160829_2011'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='category',
            field=models.CharField(choices=[('BEG', 'Beginner'), ('INT', 'Intermediate'), ('ADV', 'Advanced'), ('PRO', 'Professional'), ('MEN', 'Mens'), ('DOU', 'Doubles')], default='BEG', max_length=3),
        ),
        migrations.AlterField(
            model_name='entry',
            name='entry_year',
            field=models.CharField(choices=[('2017', '2017'), ('2018', '2018'), ('2019', '2019'), ('2020', '2020'), ('2021', '2021')], default='2018', max_length=4),
        ),
    ]
