# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-08-24 16:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entries', '0003_auto_20160820_1023'),
    ]

    operations = [
        migrations.AddField(
            model_name='entry',
            name='notified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='entry',
            name='notified_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='entry',
            name='reminder_sent',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='entry',
            name='category',
            field=models.CharField(choices=[('BEG', 'Beginner'), ('INT', 'Intermediate'), ('ADV', 'Advanced'), ('PRO', 'Professional'), ('DOU', 'Doubles'), ('MEN', 'Mens')], default='BEG', max_length=3),
        ),
        migrations.AlterField(
            model_name='entry',
            name='song',
            field=models.CharField(blank=True, help_text='Not required for initial entry submission', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='entry',
            name='status',
            field=models.CharField(choices=[('in_progress', 'In Progress'), ('submitted', 'Submitted'), ('selected', 'Selected'), ('selected_confirmed', 'Selected - confirmed'), ('rejected', 'Unsuccessful')], default='in_progress', max_length=20),
        ),
    ]
