# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-08-25 21:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entries', '0004_auto_20160824_1736'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='partner_email',
            field=models.EmailField(blank=True, help_text='Ensure this is the email your doubles partner has used for their account. We will use it to ensure registration and waiver information has been received for your partner also.', max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='entry',
            name='partner_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='entry',
            name='song',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
