# Generated by Django 2.2.5 on 2019-10-17 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entries', '0004_auto_20180508_2112'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='category',
            field=models.CharField(choices=[('BEG', 'Beginner'), ('INT', 'Intermediate'), ('ADV', 'Advanced'), ('SMP', 'Semi-Professional'), ('PRO', 'Professional'), ('MEN', 'Mens'), ('DOU', 'Doubles')], default='BEG', max_length=3),
        ),
        migrations.AlterField(
            model_name='entry',
            name='entry_year',
            field=models.CharField(choices=[('2017', '2017'), ('2018', '2018'), ('2019', '2019'), ('2020', '2020'), ('2021', '2021'), ('2022', '2022'), ('2023', '2023'), ('2024', '2024'), ('2025', '2025'), ('2026', '2026'), ('2027', '2027'), ('2028', '2028'), ('2029', '2029'), ('2030', '2030')], default='2020', max_length=4),
        ),
    ]
