# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-08-26 21:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entries', '0005_auto_20160825_2201'),
    ]

    operations = [
        migrations.AddField(
            model_name='entry',
            name='withdrawal_fee_paid',
            field=models.BooleanField(default=False),
        ),
    ]
