# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-08-27 13:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entries', '0007_auto_20160827_1333'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='status',
            field=models.CharField(choices=[('in_progress', 'In Progress'), ('submitted', 'Submitted'), ('selected', 'Selected'), ('selected_confirmed', 'Selected - confirmed'), ('rejected', 'Rejected')], default='in_progress', max_length=20),
        ),
    ]
