# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-08-29 11:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entries', '0008_auto_20160827_1403'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='video_url',
            field=models.URLField(blank=True, default='', null=True),
        ),
    ]
