"""
Django settings for pole_performance project.

Generated by 'django-admin startproject' using Django 1.9.8.

For more information on this file, see
https://docs.djangoproject.com/en/1.9/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/1.9/ref/settings/
"""
import environ
import os
import sys

root = environ.Path(__file__) - 2  # two folders back (/a/b/ - 3 = /)
env = environ.Env(DEBUG=(bool, False),
                  PAYPAL_TEST=(bool, False),
                  USE_MAILCATCHER=(bool, False),
                  TRAVIS=(bool, False),
                  HEROKU=(bool, False),
                  ENTRIES_OPEN=(bool, False),
                  SHOW_DEBUG_TOOLBAR=(bool, False),
                  LOCAL=(bool, False)
                  )
environ.Env.read_env(root('poleperformance/.env'))  # reading .env file

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = root()


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/1.9/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = env('SECRET_KEY')
if SECRET_KEY is None:  # pragma: no cover
    print("No secret key!")

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = env('DEBUG')
# when env variable is changed it will be a string, not bool
if str(DEBUG).lower() in ['true', 'on']:  # pragma: no cover
    DEBUG = True
else:   # pragma: no cover
    DEBUG = False

ALLOWED_HOSTS = ['.poleperformancecomp.co.uk']
if env('LOCAL'):  # pragma: no cover
    ALLOWED_HOSTS = ['*']

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.sites',
    'cookielaw',
    'allauth',
    'allauth.account',
    'debug_toolbar',
    'crispy_forms',
    'django_extensions',
    'paypal.standard.ipn',
    'web',
    'activitylog',
    'accounts',
    'entries',
    'payments',
    'ppadmin'
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'debug_toolbar.middleware.DebugToolbarMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

SITE_ID = 1


CACHES = {
    'default': {
        'BACKEND': 'django.core.cache.backends.memcached.MemcachedCache',
        'LOCATION': '127.0.0.1:11211',
    }
}


AUTHENTICATION_BACKENDS = (
    # Needed to login by username in Django admin, regardless of `allauth`
    "django.contrib.auth.backends.ModelBackend",

    # `allauth` specific authentication methods, such as login by e-mail
    "allauth.account.auth_backends.AuthenticationBackend",
)

# SOCIALACCOUNT_PROVIDERS = \
#     {'facebook': {
#         'SCOPE': ['email'],
#         # 'AUTH_PARAMS': {'auth_type': 'reauthenticate'},
#         'METHOD': 'oauth2',
#         'VERIFIED_EMAIL': False,
#         'VERSION': 'v2.2'
#         }}


ACCOUNT_AUTHENTICATION_METHOD = "username_email"
ACCOUNT_EMAIL_REQUIRED = True
ACCOUNT_EMAIL_VERIFICATION = "mandatory"
ACCOUNT_EMAIL_SUBJECT_PREFIX = "[Pole Performance]"
ACCOUNT_SIGNUP_FORM_CLASS = 'accounts.forms.SignupForm'
ACCOUNT_LOGOUT_REDIRECT_URL ="/entries"
ACCOUNT_LOGIN_ON_EMAIL_CONFIRMATION = True
ACCOUNT_PRESERVE_USERNAME_CASING = False
# SOCIALACCOUNT_QUERY_EMAIL = True


ROOT_URLCONF = 'poleperformance.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [root('templates')],
        # 'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'entries.context_processors.pp_email',
                'entries.context_processors.entries',
            ],
            'loaders': [
                'apptemplates.Loader',
                'django.template.loaders.filesystem.Loader',
                'django.template.loaders.app_directories.Loader',
            ]
        },
    },
]

# ABSOLUTE_URL_OVERRIDES = {
#     'auth.user': lambda o: "/users/%s/" % o.username,
# }

WSGI_APPLICATION = 'poleperformance.wsgi.application'


# Database
# https://docs.djangoproject.com/en/1.9/ref/settings/#databases

DATABASES = {
    'default': env.db(),
}


# Password validation
# https://docs.djangoproject.com/en/1.9/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/1.9/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'Europe/London'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/1.9/howto/static-files/
STATIC_URL = '/static/'

STATIC_ROOT = root('collected-static')

MEDIA_URL = '/media/'
MEDIA_ROOT = root('media')


EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_USE_TLS = True
EMAIL_HOST = 'smtp.gmail.com'
EMAIL_HOST_USER = 'poleperformance.web@gmail.com'
EMAIL_HOST_PASSWORD = env('EMAIL_HOST_PASSWORD', None)
if EMAIL_HOST_PASSWORD is None:  # pragma: no cover
    print("No email host password provided!")
EMAIL_PORT = 587
DEFAULT_FROM_EMAIL = 'poleperformance.web@gmail.com'
DEFAULT_STUDIO_EMAIL = env('DEFAULT_STUDIO_EMAIL')
SUPPORT_EMAIL = 'rebkwok@gmail.com'


# #####LOGGING######
LOG_FOLDER = env('LOG_FOLDER')

LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'verbose': {
            'format': '[%(levelname)s] - %(asctime)s - %(name)s - '
                      '%(message)s',
            'datefmt': '%Y-%m-%d %H:%M:%S',
        }
    },
    'handlers': {
        'file_app': {
            'level': 'INFO',
            'class': 'logging.handlers.RotatingFileHandler',
            'filename': os.path.join(LOG_FOLDER, 'poleperformance.log'),
            'maxBytes': 1024*1024*5,  # 5 MB
            'backupCount': 5,
            'formatter': 'verbose'
        },
        'console': {
            'level': 'DEBUG',
            'class': 'logging.StreamHandler',
            'formatter': 'verbose'
        },
        'mail_admins': {
            'level': 'ERROR',
            'class': 'django.utils.log.AdminEmailHandler',
            'include_html': True,
        },
    },
    'loggers': {
        '': {
            'handlers': ['console', 'file_app', 'mail_admins'],
            'level': 'WARNING',
            'propagate': True,
        },
        'accounts': {
            'handlers': ['console', 'file_app', 'mail_admins'],
            'level': 'INFO',
            'propagate': False,
        },
        'web': {
            'handlers': ['console', 'file_app', 'mail_admins'],
            'level': 'INFO',
            'propagate': False,
        },
        'entries': {
            'handlers': ['console', 'file_app', 'mail_admins'],
            'level': 'INFO',
            'propagate': False,
        },
        'payments': {
            'handlers': ['console', 'file_app', 'mail_admins'],
            'level': 'INFO',
            'propagate': False,
        },
        'activitylog': {
            'handlers': ['console', 'file_app', 'mail_admins'],
            'level': 'INFO',
            'propagate': False,
        },
        'ppadmin': {
            'handlers': ['console', 'file_app', 'mail_admins'],
            'level': 'INFO',
            'propagate': False,
        },

    },
}

ADMINS = [("Becky Smith", SUPPORT_EMAIL)]

import sys
if DEBUG or 'test' in sys.argv:   # pragma: no cover
    LOGGING['loggers'] = {
        '': {
            'handlers': ['console', 'file_app'],
            'level': 'WARNING',
            'propagate': True,
        }
    }
# ####HEROKU#######

HEROKU = env('HEROKU')

# Honor the 'X-Forwarded-Proto' header for request.is_secure()
SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')


INTERNAL_IPS = ('127.0.0.1',)


# MAILCATCHER
if env('USE_MAILCATCHER'):  # pragma: no cover
    EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
    EMAIL_HOST = '127.0.0.1'
    EMAIL_HOST_USER = ''
    EMAIL_HOST_PASSWORD = ''
    EMAIL_PORT = 1025
    EMAIL_USE_TLS = False


# DJANGO-PAYPAL
DEFAULT_PAYPAL_EMAIL = env('DEFAULT_PAYPAL_EMAIL')
PAYPAL_TEST = env('PAYPAL_TEST')


if 'test' in sys.argv:  # use local cache for tests
    CACHES = {
        'default': {
            'BACKEND': 'django.core.cache.backends.locmem.LocMemCache',
            'LOCATION': 'test-cache',
        }
    }


ENTRIES_OPEN_DATE = env('ENTRIES_OPEN_DATE')
ENTRIES_CLOSE_DATE = env('ENTRIES_CLOSE_DATE')
LATE_CATEGORIES_ENTRIES_CLOSE_DATE = env('LATE_CATEGORIES_ENTRIES_CLOSE_DATE')

CURRENT_ENTRY_YEAR = env('CURRENT_ENTRY_YEAR')

FINAL_DATE = env('FINAL_DATE')
FINAL_TIMES = env('FINAL_TIMES')

if env('SHOW_DEBUG_TOOLBAR') and 'test' not in sys.argv:  # pragma: no cover
    def show_toolbar(request):
        return True
    DEBUG_TOOLBAR_PATCH_SETTINGS = False
    DEBUG_TOOLBAR_CONFIG = {
        "SHOW_TOOLBAR_CALLBACK": show_toolbar,
    }


# Activitylogs
EMPTY_JOB_TEXT = ['CRON: Auto warn/withdraw selected unconfirmed/unpaid run: no action required']

S3_LOG_BACKUP_PATH = "s3://backups.polefitstarlet.co.uk/poleperformance_activitylogs"
S3_LOG_BACKUP_ROOT_FILENAME = "poleperformance_activity_logs_backup"
